### ISSUE TITLE
Gitter integration with GitHub

### ISSUE THREAD

**Issue by timtim17** [FRC-1294/frc2016#24]
@blueal Apparently Gitter integration is not working for me - maybe since I don't have owner privileges I can't setup the webhooks. Can you?

![gitter](https://cloud.githubusercontent.com/assets/6354860/12725262/ac3dc1ba-c8c6-11e5-8080-5b9454972da8.PNG)

**Comment by blueal** [comment]
I need to approve access to get those things to work. ![screenshot_2016-02-01-09-39-10](https://cloud.githubusercontent.com/assets/4614311/12725493/d8057922-c8c7-11e5-8cfe-28be625dc8f7.png)

**Comment by timtim17** [comment]
Supposedly it's already approved, but all I could see was my own repos.

![g](https://cloud.githubusercontent.com/assets/6354860/12726130/bd12cd6a-c8ca-11e5-95bb-cf1db6a92db6.PNG)

**Comment by timtim17** [comment]
Email received 8:35 PM yesterday.
![o](https://cloud.githubusercontent.com/assets/6354860/12726260/8f5cf8a4-c8cb-11e5-87dc-0cf1f0e413d5.PNG)
