### ISSUE TITLE
Re-enable releasing to bintray

### ISSUE THREAD

**Issue by timtim17** [FRC-1294/frc2016#6]
While adding the basic robot project, I commented out some of the bintray stuff because I didn't think bintray would work with the new project.

I don't have much experience with pushing to bintray, but I think I could figure it out.

Also, it might be a good idea to set up a [team bintray organization account](https://bintray.com/docs/usermanual/interacting/interacting_bintrayorganizations.html), instead of deploying to a specific person's account. We should also possibly see if we can [move bintray uploading to `.travis.yml`](https://docs.travis-ci.com/user/deployment/bintray) instead of having it as a task in gradle.

**Comment by JohnRudolfLewis** [comment]
I agree that we should not use my personal account. Who wants to create the
new account? And after that, just let me know if you need any help in
getting that code to work against the new account.

**Comment by timtim17** [comment]
It should probably be up to Alex, because he's pretty much admin for everything.

@blueal Can you make a [bintray organization](https://bintray.com/docs/usermanual/interacting/interacting_creatingandeditinganorganization.html) for us?

**Comment by blueal** [comment]
[Bintray Organization](https://bintray.com/frc-1294) has been imported from github
